name: Go

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21.6'

            -   name: Get dependencies
                run: go get -v -t -d ./...

            -   name: Get the version
                id: get_version
                run: echo "VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo '0.0.0')" >> $GITHUB_ENV

            -   name: Build
                run: go build -ldflags="-X main.version=$VERSION" -a -o ./build/toolbox-$VERSION -v ./main.go

            -   name: Test
                run: go test -v ./...

            -   name: Archive binary
                run: tar -czvf ./build/toolbox-$VERSION.tar.gz ./build/toolbox-$VERSION

            -   name: Upload binary as artifact
                uses: actions/upload-artifact@v2
                with:
                    name: toolbox-$VERSION
                    path: ./build/toolbox-$VERSION.tar.gz
