name: Go

on:
    create:
        tags:
            -   '*.*.*'
#    push:
#        branches: [ "master" ]
#    pull_request:
#        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21.6'

            -   name: Get dependencies
                run: go get -v -t -d ./...

            -   name: Get the version
                id: get_version
                run: |
                  echo "VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo '0.0.0')" >> $GITHUB_ENV

            -   name: GitHub Tag Name
                run: |
                    echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
                    echo "Tag name from github.ref_name: ${{  github.ref_name }}"

            -   run: mkdir -p ./build

            -   name: Build
                run: go build -ldflags="-s -w -X  main.version=$VERSION" -a -o ./build/toolbox-$VERSION -v ./main.go

            -   name: Test
                run: go test -v ./...

            -   name: Archive binary
                run: tar -czvf ./build/toolbox-$VERSION.tar.gz ./build/toolbox-$VERSION

            -   name: List files
                run: ls -la

            -   run: ls -la ./build

            -   name: Upload binary as artifact
                uses: actions/upload-artifact@v3
                with:
                    name: toolbox-$VERSION
                    path: ./build/toolbox-$VERSION.tar.gz
