name: Go

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Go 1.x
                uses: actions/setup-go@v4
                with:
                    go-version: '1.21.6'
                id: go

            -   name: Check out code into the Go module directory
                uses: actions/checkout@v2

            -   name: Get dependencies
                run: go mod download

            -   name: Build
                run: go build -v ./...

            -   name: Test
                run: go test -v ./...
